version: "3.9"
   
services:
  nginx: 
    restart: unless-stopped
    build:
        context: .
        dockerfile: ./deploy/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/backend/django_static
      - ./deploy/nginx/development:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - 5432:5432
    env_file:
      - ./prod.db.env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/backend/django_static
    stdin_open: true
    ports:
      - 8000:8000
    env_file:
      - ./dev.env
    depends_on:
      - db

volumes:
  pgdata: {}
  static_volume: {}

networks:
  app:
    driver: bridge
    name: app
    external: false